sonar.organization=fouedbenmalek_Biblioth-que-
sonar.projectKey=foueddbenmalek

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.python.version=3.12

sonar.exclusions=**/migrations/**,**/venv/**,**/static/**,**/media/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.login=986683a4cfaa5aeecfc11b2c7cc49615fe77dd9f