sonar.organization=foueddbenmalek
sonar.projectKey=fouedbenmalek_Biblioth-que-

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.python.version=3.12

sonar.exclusions=**/migrations/**,**/.venv/**,**/static/**,**/media/**
sonar.python.coverage.reportPaths=coverage.xml